name: Sync from Grok
on:
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull latest odr-auth.php
      run: |
        curl -o odr-auth.php https://pastebin.com/raw/7kP9mJqN
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Update to version 1.5.8 from Grok (fixed)"
