name: Sync from odr-sourcecode
on:
  repository_dispatch:
    types: [sync]
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Pull from odr-sourcecode
      run: |
        curl -o odr-auth.php https://raw.githubusercontent.com/fg65082001/odr-sourcecode/main/odr-auth.php
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Sync odr-auth.php from odr-sourcecode"
